language: objective-c
osx_image: xcode7
xcode_project: RCDeviceLockEvent.xcodeproj
xcode_scheme: RCDeviceLockEvent

script:
- xctool -project RCDeviceLockEvent.xcodeproj -scheme 'RCDeviceLockEvent'  build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO